version: '3'

services: 
	zookeeper:
		image: confluentinc/cp-zookeeper:5.5.1
		hostname: zookeeper
		container_name: zookeeper
		ports:
			- "2181:2181"
		environment:
			ZOOKEEPER_CLIENT_PORT: 2181
			ZOOKEEPER_TICK_TIME: 2000
		volumes:
			- $PWD/zookeeper/data:/var/lib/zookeeper/data
			- $PWD/zookeeper/logs:/var/lib/zookeeper/log
	kafka:
		image: confluentinc/cp-kafka:5.5.1
		hostname: kafka
		container_name: kafka
		ports:
			- "29092:29092"
			- "9092:9092"
		depends_on:
			- zookeeper
		environment:
			KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
			KAFKA_BROKER_ID: 1
			KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      		KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      		KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      	volumes:
      		- $PWD/kafka:/var/lib/kafka/data
    redis:
    	image: redis:latest
    	ports:
    		- "6379:6379"
    	volumes:
    		- $PWD/redis:/data
    	hostname: redis
    	container_name: redis

    http_server:
    	build: .
    	container_name: http-server
    	ports:
    		- "8080:8080"
    	depends_on:
    		- zookeeper
    		- kafka
    		- redis
